# Generated by Django 5.1.1 on 2024-10-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreport',
            options={'verbose_name': 'informe de ventas', 'verbose_name_plural': 'informe de ventas'},
        ),
    ]
