# Generated by Django 5.1.1 on 2024-09-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promocion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='shop.promocion'),
        ),
    ]
