# Generated by Django 5.1.1 on 2024-09-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_promocion_alter_promocion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promocion',
        ),
    ]
