# Generated by Django 5.1.1 on 2024-09-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='shop.promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
