# Generated by Django 5.1.1 on 2024-10-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], default='pending', max_length=10, verbose_name='Estado del pedido'),
        ),
    ]
