# Generated by Django 5.1.1 on 2024-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='directions',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones'),
        ),
        migrations.AddField(
            model_name='order',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Contra entrega'), ('pick_up', 'Yo retiro')], default='cash_on_delivery', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Número de teléfono'),
        ),
    ]
