# Generated by Django 5.1.1 on 2024-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_directions_order_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
