# Generated by Django 5.1.1 on 2024-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_directions_remove_order_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AddField(
            model_name='order',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('contraentrega', 'Pago Contraentrega'), ('retiro', 'Yo lo retiro')], default='contraentrega', max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
    ]
