# Generated by Django 5.1.1 on 2024-10-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_instructions_order_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
