# Generated by Django 5.1.1 on 2024-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad - Municipio'),
        ),
    ]
