# Generated by Django 5.1.1 on 2024-10-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_email_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Pago contra entrega'), ('pick_up', 'Yo retiro')], max_length=20, verbose_name='Forma de pago'),
        ),
    ]
