# Generated by Django 5.1.1 on 2024-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('contraentrega', 'Pago contra entrega'), ('retiro', 'Yo retiro')], max_length=20, verbose_name='Forma de pago'),
        ),
    ]
