# Generated by Django 5.1.1 on 2024-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'orden', 'verbose_name_plural': 'órdenes'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='Forma de pago'),
        ),
    ]
